//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
namespace TicketBai.Client.Schemas.TicketBaiAnula
{
    // 
    // This source code was auto-generated by xsd, Version=4.6.1055.0.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:ticketbai:anulacion")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:ticketbai:anulacion", IsNullable = false, ElementName = "AnulaTicketBai")]
    public partial class TicketBaiAnula
    {

        private Cabecera cabeceraField;

        private IDFactura iDFacturaField;

        private HuellaTBAI huellaTBAIField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Cabecera Cabecera
        {
            get
            {
                return this.cabeceraField;
            }
            set
            {
                this.cabeceraField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IDFactura IDFactura
        {
            get
            {
                return this.iDFacturaField;
            }
            set
            {
                this.iDFacturaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public HuellaTBAI HuellaTBAI
        {
            get
            {
                return this.huellaTBAIField;
            }
            set
            {
                this.huellaTBAIField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ticketbai:anulacion")]
    public partial class Cabecera
    {

        private IDVersionTicketBaiType iDVersionTBAIField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IDVersionTicketBaiType IDVersionTBAI
        {
            get
            {
                return this.iDVersionTBAIField;
            }
            set
            {
                this.iDVersionTBAIField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ticketbai:anulacion")]
    public enum IDVersionTicketBaiType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1.2")]
        Item12,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ticketbai:anulacion")]
    public partial class IDOtro
    {

        private CountryType2 codigoPaisField;

        private bool codigoPaisFieldSpecified;

        private IDTypeType iDTypeField;

        private string idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CountryType2 CodigoPais
        {
            get
            {
                return this.codigoPaisField;
            }
            set
            {
                this.codigoPaisField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CodigoPaisSpecified
        {
            get
            {
                return this.codigoPaisFieldSpecified;
            }
            set
            {
                this.codigoPaisFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IDTypeType IDType
        {
            get
            {
                return this.iDTypeField;
            }
            set
            {
                this.iDTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ticketbai:anulacion")]
    public enum CountryType2
    {

        /// <remarks/>
        AF,

        /// <remarks/>
        AL,

        /// <remarks/>
        DE,

        /// <remarks/>
        AD,

        /// <remarks/>
        AO,

        /// <remarks/>
        AI,

        /// <remarks/>
        AQ,

        /// <remarks/>
        AG,

        /// <remarks/>
        SA,

        /// <remarks/>
        DZ,

        /// <remarks/>
        AR,

        /// <remarks/>
        AM,

        /// <remarks/>
        AW,

        /// <remarks/>
        AU,

        /// <remarks/>
        AT,

        /// <remarks/>
        AZ,

        /// <remarks/>
        BS,

        /// <remarks/>
        BH,

        /// <remarks/>
        BD,

        /// <remarks/>
        BB,

        /// <remarks/>
        BE,

        /// <remarks/>
        BZ,

        /// <remarks/>
        BJ,

        /// <remarks/>
        BM,

        /// <remarks/>
        BY,

        /// <remarks/>
        BO,

        /// <remarks/>
        BA,

        /// <remarks/>
        BW,

        /// <remarks/>
        BV,

        /// <remarks/>
        BR,

        /// <remarks/>
        BN,

        /// <remarks/>
        BG,

        /// <remarks/>
        BF,

        /// <remarks/>
        BI,

        /// <remarks/>
        BT,

        /// <remarks/>
        CV,

        /// <remarks/>
        KY,

        /// <remarks/>
        KH,

        /// <remarks/>
        CM,

        /// <remarks/>
        CA,

        /// <remarks/>
        CF,

        /// <remarks/>
        CC,

        /// <remarks/>
        CO,

        /// <remarks/>
        KM,

        /// <remarks/>
        CG,

        /// <remarks/>
        CD,

        /// <remarks/>
        CK,

        /// <remarks/>
        KP,

        /// <remarks/>
        KR,

        /// <remarks/>
        CI,

        /// <remarks/>
        CR,

        /// <remarks/>
        HR,

        /// <remarks/>
        CU,

        /// <remarks/>
        TD,

        /// <remarks/>
        CZ,

        /// <remarks/>
        CL,

        /// <remarks/>
        CN,

        /// <remarks/>
        CY,

        /// <remarks/>
        CW,

        /// <remarks/>
        DK,

        /// <remarks/>
        DM,

        /// <remarks/>
        DO,

        /// <remarks/>
        EC,

        /// <remarks/>
        EG,

        /// <remarks/>
        AE,

        /// <remarks/>
        ER,

        /// <remarks/>
        SK,

        /// <remarks/>
        SI,

        /// <remarks/>
        ES,

        /// <remarks/>
        US,

        /// <remarks/>
        EE,

        /// <remarks/>
        ET,

        /// <remarks/>
        FO,

        /// <remarks/>
        PH,

        /// <remarks/>
        FI,

        /// <remarks/>
        FJ,

        /// <remarks/>
        FR,

        /// <remarks/>
        GA,

        /// <remarks/>
        GM,

        /// <remarks/>
        GE,

        /// <remarks/>
        GS,

        /// <remarks/>
        GH,

        /// <remarks/>
        GI,

        /// <remarks/>
        GD,

        /// <remarks/>
        GR,

        /// <remarks/>
        GL,

        /// <remarks/>
        GU,

        /// <remarks/>
        GT,

        /// <remarks/>
        GG,

        /// <remarks/>
        GN,

        /// <remarks/>
        GQ,

        /// <remarks/>
        GW,

        /// <remarks/>
        GY,

        /// <remarks/>
        HT,

        /// <remarks/>
        HM,

        /// <remarks/>
        HN,

        /// <remarks/>
        HK,

        /// <remarks/>
        HU,

        /// <remarks/>
        IN,

        /// <remarks/>
        ID,

        /// <remarks/>
        IR,

        /// <remarks/>
        IQ,

        /// <remarks/>
        IE,

        /// <remarks/>
        IM,

        /// <remarks/>
        IS,

        /// <remarks/>
        IL,

        /// <remarks/>
        IT,

        /// <remarks/>
        JM,

        /// <remarks/>
        JP,

        /// <remarks/>
        JE,

        /// <remarks/>
        JO,

        /// <remarks/>
        KZ,

        /// <remarks/>
        KE,

        /// <remarks/>
        KG,

        /// <remarks/>
        KI,

        /// <remarks/>
        KW,

        /// <remarks/>
        LA,

        /// <remarks/>
        LS,

        /// <remarks/>
        LV,

        /// <remarks/>
        LB,

        /// <remarks/>
        LR,

        /// <remarks/>
        LY,

        /// <remarks/>
        LI,

        /// <remarks/>
        LT,

        /// <remarks/>
        LU,

        /// <remarks/>
        XG,

        /// <remarks/>
        MO,

        /// <remarks/>
        MK,

        /// <remarks/>
        MG,

        /// <remarks/>
        MY,

        /// <remarks/>
        MW,

        /// <remarks/>
        MV,

        /// <remarks/>
        ML,

        /// <remarks/>
        MT,

        /// <remarks/>
        FK,

        /// <remarks/>
        MP,

        /// <remarks/>
        MA,

        /// <remarks/>
        MH,

        /// <remarks/>
        MU,

        /// <remarks/>
        MR,

        /// <remarks/>
        YT,

        /// <remarks/>
        UM,

        /// <remarks/>
        MX,

        /// <remarks/>
        FM,

        /// <remarks/>
        MD,

        /// <remarks/>
        MC,

        /// <remarks/>
        MN,

        /// <remarks/>
        ME,

        /// <remarks/>
        MS,

        /// <remarks/>
        MZ,

        /// <remarks/>
        MM,

        /// <remarks/>
        NA,

        /// <remarks/>
        NR,

        /// <remarks/>
        CX,

        /// <remarks/>
        NP,

        /// <remarks/>
        NI,

        /// <remarks/>
        NE,

        /// <remarks/>
        NG,

        /// <remarks/>
        NU,

        /// <remarks/>
        NF,

        /// <remarks/>
        NO,

        /// <remarks/>
        NC,

        /// <remarks/>
        NZ,

        /// <remarks/>
        IO,

        /// <remarks/>
        OM,

        /// <remarks/>
        NL,

        /// <remarks/>
        BQ,

        /// <remarks/>
        PK,

        /// <remarks/>
        PW,

        /// <remarks/>
        PA,

        /// <remarks/>
        PG,

        /// <remarks/>
        PY,

        /// <remarks/>
        PE,

        /// <remarks/>
        PN,

        /// <remarks/>
        PF,

        /// <remarks/>
        PL,

        /// <remarks/>
        PT,

        /// <remarks/>
        PR,

        /// <remarks/>
        QA,

        /// <remarks/>
        GB,

        /// <remarks/>
        RW,

        /// <remarks/>
        RO,

        /// <remarks/>
        RU,

        /// <remarks/>
        SB,

        /// <remarks/>
        SV,

        /// <remarks/>
        WS,

        /// <remarks/>
        AS,

        /// <remarks/>
        KN,

        /// <remarks/>
        SM,

        /// <remarks/>
        SX,

        /// <remarks/>
        PM,

        /// <remarks/>
        VC,

        /// <remarks/>
        SH,

        /// <remarks/>
        LC,

        /// <remarks/>
        ST,

        /// <remarks/>
        SN,

        /// <remarks/>
        RS,

        /// <remarks/>
        SC,

        /// <remarks/>
        SL,

        /// <remarks/>
        SG,

        /// <remarks/>
        SY,

        /// <remarks/>
        SO,

        /// <remarks/>
        LK,

        /// <remarks/>
        SZ,

        /// <remarks/>
        ZA,

        /// <remarks/>
        SD,

        /// <remarks/>
        SS,

        /// <remarks/>
        SE,

        /// <remarks/>
        CH,

        /// <remarks/>
        SR,

        /// <remarks/>
        TH,

        /// <remarks/>
        TW,

        /// <remarks/>
        TZ,

        /// <remarks/>
        TJ,

        /// <remarks/>
        PS,

        /// <remarks/>
        TF,

        /// <remarks/>
        TL,

        /// <remarks/>
        TG,

        /// <remarks/>
        TK,

        /// <remarks/>
        TO,

        /// <remarks/>
        TT,

        /// <remarks/>
        TN,

        /// <remarks/>
        TC,

        /// <remarks/>
        TM,

        /// <remarks/>
        TR,

        /// <remarks/>
        TV,

        /// <remarks/>
        UA,

        /// <remarks/>
        UG,

        /// <remarks/>
        UY,

        /// <remarks/>
        UZ,

        /// <remarks/>
        VU,

        /// <remarks/>
        VA,

        /// <remarks/>
        VE,

        /// <remarks/>
        VN,

        /// <remarks/>
        VG,

        /// <remarks/>
        VI,

        /// <remarks/>
        WF,

        /// <remarks/>
        YE,

        /// <remarks/>
        DJ,

        /// <remarks/>
        ZM,

        /// <remarks/>
        ZW,

        /// <remarks/>
        QU,

        /// <remarks/>
        XB,

        /// <remarks/>
        XU,

        /// <remarks/>
        XN,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ticketbai:anulacion")]
    public enum IDTypeType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("02")]
        Item02,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("03")]
        Item03,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("04")]
        Item04,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("05")]
        Item05,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("06")]
        Item06,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ticketbai:anulacion")]
    public partial class EntidadDesarrolladoraType
    {

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IDOtro", typeof(IDOtro), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("NIF", typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ticketbai:anulacion")]
    public partial class SoftwareFacturacionType
    {

        private string licenciaTBAIField;

        private EntidadDesarrolladoraType entidadDesarrolladoraField;

        private string nombreField;

        private string versionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LicenciaTBAI
        {
            get
            {
                return this.licenciaTBAIField;
            }
            set
            {
                this.licenciaTBAIField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntidadDesarrolladoraType EntidadDesarrolladora
        {
            get
            {
                return this.entidadDesarrolladoraField;
            }
            set
            {
                this.entidadDesarrolladoraField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ticketbai:anulacion")]
    public partial class HuellaTBAI
    {

        private SoftwareFacturacionType softwareField;

        private string numSerieDispositivoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftwareFacturacionType Software
        {
            get
            {
                return this.softwareField;
            }
            set
            {
                this.softwareField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NumSerieDispositivo
        {
            get
            {
                return this.numSerieDispositivoField;
            }
            set
            {
                this.numSerieDispositivoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ticketbai:anulacion")]
    public partial class CabeceraFacturaType
    {

        private string serieFacturaField;

        private string numFacturaField;

        private string fechaExpedicionFacturaField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SerieFactura
        {
            get
            {
                return this.serieFacturaField;
            }
            set
            {
                this.serieFacturaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NumFactura
        {
            get
            {
                return this.numFacturaField;
            }
            set
            {
                this.numFacturaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FechaExpedicionFactura
        {
            get
            {
                return this.fechaExpedicionFacturaField;
            }
            set
            {
                this.fechaExpedicionFacturaField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ticketbai:anulacion")]
    public partial class Emisor
    {

        private string nIFField;

        private string apellidosNombreRazonSocialField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NIF
        {
            get
            {
                return this.nIFField;
            }
            set
            {
                this.nIFField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ApellidosNombreRazonSocial
        {
            get
            {
                return this.apellidosNombreRazonSocialField;
            }
            set
            {
                this.apellidosNombreRazonSocialField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ticketbai:anulacion")]
    public partial class IDFactura
    {

        private Emisor emisorField;

        private CabeceraFacturaType cabeceraFacturaField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Emisor Emisor
        {
            get
            {
                return this.emisorField;
            }
            set
            {
                this.emisorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CabeceraFacturaType CabeceraFactura
        {
            get
            {
                return this.cabeceraFacturaField;
            }
            set
            {
                this.cabeceraFacturaField = value;
            }
        }
    }
}