
namespace TicketBai.Client.Schemas.TicketBaiRequest
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    //     Runtime Version:4.0.30319.42000
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------

    // 
    // This source code was auto-generated by xsd, Version=4.6.1055.0.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:ticketbai:emision")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:ticketbai:emision", IsNullable = false, ElementName = "TicketBai")]
    public partial class TicketBaiRequest
    {

        private Cabecera cabeceraField;

        private Sujetos sujetosField;

        private Factura facturaField;

        private HuellaTBAI huellaTBAIField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Cabecera Cabecera
        {
            get
            {
                return this.cabeceraField;
            }
            set
            {
                this.cabeceraField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Sujetos Sujetos
        {
            get
            {
                return this.sujetosField;
            }
            set
            {
                this.sujetosField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Factura Factura
        {
            get
            {
                return this.facturaField;
            }
            set
            {
                this.facturaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public HuellaTBAI HuellaTBAI
        {
            get
            {
                return this.huellaTBAIField;
            }
            set
            {
                this.huellaTBAIField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ticketbai:emision")]
    public partial class Cabecera
    {

        private IDVersionTicketBaiType iDVersionTBAIField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IDVersionTicketBaiType IDVersionTBAI
        {
            get
            {
                return this.iDVersionTBAIField;
            }
            set
            {
                this.iDVersionTBAIField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ticketbai:emision")]
    public enum IDVersionTicketBaiType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1.2")]
        Item12,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ticketbai:emision")]
    public partial class EntidadDesarrolladoraType
    {

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IDOtro", typeof(IDOtro), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("NIF", typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ticketbai:emision")]
    public partial class IDOtro
    {

        private CountryType2 codigoPaisField;

        private bool codigoPaisFieldSpecified;

        private IDTypeType iDTypeField;

        private string idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CountryType2 CodigoPais
        {
            get
            {
                return this.codigoPaisField;
            }
            set
            {
                this.codigoPaisField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CodigoPaisSpecified
        {
            get
            {
                return this.codigoPaisFieldSpecified;
            }
            set
            {
                this.codigoPaisFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IDTypeType IDType
        {
            get
            {
                return this.iDTypeField;
            }
            set
            {
                this.iDTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ticketbai:emision")]
    public enum CountryType2
    {

        /// <remarks/>
        AF,

        /// <remarks/>
        AL,

        /// <remarks/>
        DE,

        /// <remarks/>
        AD,

        /// <remarks/>
        AO,

        /// <remarks/>
        AI,

        /// <remarks/>
        AQ,

        /// <remarks/>
        AG,

        /// <remarks/>
        SA,

        /// <remarks/>
        DZ,

        /// <remarks/>
        AR,

        /// <remarks/>
        AM,

        /// <remarks/>
        AW,

        /// <remarks/>
        AU,

        /// <remarks/>
        AT,

        /// <remarks/>
        AZ,

        /// <remarks/>
        BS,

        /// <remarks/>
        BH,

        /// <remarks/>
        BD,

        /// <remarks/>
        BB,

        /// <remarks/>
        BE,

        /// <remarks/>
        BZ,

        /// <remarks/>
        BJ,

        /// <remarks/>
        BM,

        /// <remarks/>
        BY,

        /// <remarks/>
        BO,

        /// <remarks/>
        BA,

        /// <remarks/>
        BW,

        /// <remarks/>
        BV,

        /// <remarks/>
        BR,

        /// <remarks/>
        BN,

        /// <remarks/>
        BG,

        /// <remarks/>
        BF,

        /// <remarks/>
        BI,

        /// <remarks/>
        BT,

        /// <remarks/>
        CV,

        /// <remarks/>
        KY,

        /// <remarks/>
        KH,

        /// <remarks/>
        CM,

        /// <remarks/>
        CA,

        /// <remarks/>
        CF,

        /// <remarks/>
        CC,

        /// <remarks/>
        CO,

        /// <remarks/>
        KM,

        /// <remarks/>
        CG,

        /// <remarks/>
        CD,

        /// <remarks/>
        CK,

        /// <remarks/>
        KP,

        /// <remarks/>
        KR,

        /// <remarks/>
        CI,

        /// <remarks/>
        CR,

        /// <remarks/>
        HR,

        /// <remarks/>
        CU,

        /// <remarks/>
        TD,

        /// <remarks/>
        CZ,

        /// <remarks/>
        CL,

        /// <remarks/>
        CN,

        /// <remarks/>
        CY,

        /// <remarks/>
        CW,

        /// <remarks/>
        DK,

        /// <remarks/>
        DM,

        /// <remarks/>
        DO,

        /// <remarks/>
        EC,

        /// <remarks/>
        EG,

        /// <remarks/>
        AE,

        /// <remarks/>
        ER,

        /// <remarks/>
        SK,

        /// <remarks/>
        SI,

        /// <remarks/>
        ES,

        /// <remarks/>
        US,

        /// <remarks/>
        EE,

        /// <remarks/>
        ET,

        /// <remarks/>
        FO,

        /// <remarks/>
        PH,

        /// <remarks/>
        FI,

        /// <remarks/>
        FJ,

        /// <remarks/>
        FR,

        /// <remarks/>
        GA,

        /// <remarks/>
        GM,

        /// <remarks/>
        GE,

        /// <remarks/>
        GS,

        /// <remarks/>
        GH,

        /// <remarks/>
        GI,

        /// <remarks/>
        GD,

        /// <remarks/>
        GR,

        /// <remarks/>
        GL,

        /// <remarks/>
        GU,

        /// <remarks/>
        GT,

        /// <remarks/>
        GG,

        /// <remarks/>
        GN,

        /// <remarks/>
        GQ,

        /// <remarks/>
        GW,

        /// <remarks/>
        GY,

        /// <remarks/>
        HT,

        /// <remarks/>
        HM,

        /// <remarks/>
        HN,

        /// <remarks/>
        HK,

        /// <remarks/>
        HU,

        /// <remarks/>
        IN,

        /// <remarks/>
        ID,

        /// <remarks/>
        IR,

        /// <remarks/>
        IQ,

        /// <remarks/>
        IE,

        /// <remarks/>
        IM,

        /// <remarks/>
        IS,

        /// <remarks/>
        IL,

        /// <remarks/>
        IT,

        /// <remarks/>
        JM,

        /// <remarks/>
        JP,

        /// <remarks/>
        JE,

        /// <remarks/>
        JO,

        /// <remarks/>
        KZ,

        /// <remarks/>
        KE,

        /// <remarks/>
        KG,

        /// <remarks/>
        KI,

        /// <remarks/>
        KW,

        /// <remarks/>
        LA,

        /// <remarks/>
        LS,

        /// <remarks/>
        LV,

        /// <remarks/>
        LB,

        /// <remarks/>
        LR,

        /// <remarks/>
        LY,

        /// <remarks/>
        LI,

        /// <remarks/>
        LT,

        /// <remarks/>
        LU,

        /// <remarks/>
        XG,

        /// <remarks/>
        MO,

        /// <remarks/>
        MK,

        /// <remarks/>
        MG,

        /// <remarks/>
        MY,

        /// <remarks/>
        MW,

        /// <remarks/>
        MV,

        /// <remarks/>
        ML,

        /// <remarks/>
        MT,

        /// <remarks/>
        FK,

        /// <remarks/>
        MP,

        /// <remarks/>
        MA,

        /// <remarks/>
        MH,

        /// <remarks/>
        MU,

        /// <remarks/>
        MR,

        /// <remarks/>
        YT,

        /// <remarks/>
        UM,

        /// <remarks/>
        MX,

        /// <remarks/>
        FM,

        /// <remarks/>
        MD,

        /// <remarks/>
        MC,

        /// <remarks/>
        MN,

        /// <remarks/>
        ME,

        /// <remarks/>
        MS,

        /// <remarks/>
        MZ,

        /// <remarks/>
        MM,

        /// <remarks/>
        NA,

        /// <remarks/>
        NR,

        /// <remarks/>
        CX,

        /// <remarks/>
        NP,

        /// <remarks/>
        NI,

        /// <remarks/>
        NE,

        /// <remarks/>
        NG,

        /// <remarks/>
        NU,

        /// <remarks/>
        NF,

        /// <remarks/>
        NO,

        /// <remarks/>
        NC,

        /// <remarks/>
        NZ,

        /// <remarks/>
        IO,

        /// <remarks/>
        OM,

        /// <remarks/>
        NL,

        /// <remarks/>
        BQ,

        /// <remarks/>
        PK,

        /// <remarks/>
        PW,

        /// <remarks/>
        PA,

        /// <remarks/>
        PG,

        /// <remarks/>
        PY,

        /// <remarks/>
        PE,

        /// <remarks/>
        PN,

        /// <remarks/>
        PF,

        /// <remarks/>
        PL,

        /// <remarks/>
        PT,

        /// <remarks/>
        PR,

        /// <remarks/>
        QA,

        /// <remarks/>
        GB,

        /// <remarks/>
        RW,

        /// <remarks/>
        RO,

        /// <remarks/>
        RU,

        /// <remarks/>
        SB,

        /// <remarks/>
        SV,

        /// <remarks/>
        WS,

        /// <remarks/>
        AS,

        /// <remarks/>
        KN,

        /// <remarks/>
        SM,

        /// <remarks/>
        SX,

        /// <remarks/>
        PM,

        /// <remarks/>
        VC,

        /// <remarks/>
        SH,

        /// <remarks/>
        LC,

        /// <remarks/>
        ST,

        /// <remarks/>
        SN,

        /// <remarks/>
        RS,

        /// <remarks/>
        SC,

        /// <remarks/>
        SL,

        /// <remarks/>
        SG,

        /// <remarks/>
        SY,

        /// <remarks/>
        SO,

        /// <remarks/>
        LK,

        /// <remarks/>
        SZ,

        /// <remarks/>
        ZA,

        /// <remarks/>
        SD,

        /// <remarks/>
        SS,

        /// <remarks/>
        SE,

        /// <remarks/>
        CH,

        /// <remarks/>
        SR,

        /// <remarks/>
        TH,

        /// <remarks/>
        TW,

        /// <remarks/>
        TZ,

        /// <remarks/>
        TJ,

        /// <remarks/>
        PS,

        /// <remarks/>
        TF,

        /// <remarks/>
        TL,

        /// <remarks/>
        TG,

        /// <remarks/>
        TK,

        /// <remarks/>
        TO,

        /// <remarks/>
        TT,

        /// <remarks/>
        TN,

        /// <remarks/>
        TC,

        /// <remarks/>
        TM,

        /// <remarks/>
        TR,

        /// <remarks/>
        TV,

        /// <remarks/>
        UA,

        /// <remarks/>
        UG,

        /// <remarks/>
        UY,

        /// <remarks/>
        UZ,

        /// <remarks/>
        VU,

        /// <remarks/>
        VA,

        /// <remarks/>
        VE,

        /// <remarks/>
        VN,

        /// <remarks/>
        VG,

        /// <remarks/>
        VI,

        /// <remarks/>
        WF,

        /// <remarks/>
        YE,

        /// <remarks/>
        DJ,

        /// <remarks/>
        ZM,

        /// <remarks/>
        ZW,

        /// <remarks/>
        QU,

        /// <remarks/>
        XB,

        /// <remarks/>
        XU,

        /// <remarks/>
        XN,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ticketbai:emision")]
    public enum IDTypeType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("02")]
        Item02,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("03")]
        Item03,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("04")]
        Item04,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("05")]
        Item05,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("06")]
        Item06,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ticketbai:emision")]
    public partial class SoftwareFacturacionType
    {

        private string licenciaTBAIField;

        private EntidadDesarrolladoraType entidadDesarrolladoraField;

        private string nombreField;

        private string versionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LicenciaTBAI
        {
            get
            {
                return this.licenciaTBAIField;
            }
            set
            {
                this.licenciaTBAIField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntidadDesarrolladoraType EntidadDesarrolladora
        {
            get
            {
                return this.entidadDesarrolladoraField;
            }
            set
            {
                this.entidadDesarrolladoraField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ticketbai:emision")]
    public partial class EncadenamientoFacturaAnteriorType
    {

        private string serieFacturaAnteriorField;

        private string numFacturaAnteriorField;

        private string fechaExpedicionFacturaAnteriorField;

        private string signatureValueFirmaFacturaAnteriorField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SerieFacturaAnterior
        {
            get
            {
                return this.serieFacturaAnteriorField;
            }
            set
            {
                this.serieFacturaAnteriorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NumFacturaAnterior
        {
            get
            {
                return this.numFacturaAnteriorField;
            }
            set
            {
                this.numFacturaAnteriorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FechaExpedicionFacturaAnterior
        {
            get
            {
                return this.fechaExpedicionFacturaAnteriorField;
            }
            set
            {
                this.fechaExpedicionFacturaAnteriorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SignatureValueFirmaFacturaAnterior
        {
            get
            {
                return this.signatureValueFirmaFacturaAnteriorField;
            }
            set
            {
                this.signatureValueFirmaFacturaAnteriorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ticketbai:emision")]
    public partial class HuellaTBAI
    {

        private EncadenamientoFacturaAnteriorType encadenamientoFacturaAnteriorField;

        private SoftwareFacturacionType softwareField;

        private string numSerieDispositivoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EncadenamientoFacturaAnteriorType EncadenamientoFacturaAnterior
        {
            get
            {
                return this.encadenamientoFacturaAnteriorField;
            }
            set
            {
                this.encadenamientoFacturaAnteriorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftwareFacturacionType Software
        {
            get
            {
                return this.softwareField;
            }
            set
            {
                this.softwareField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NumSerieDispositivo
        {
            get
            {
                return this.numSerieDispositivoField;
            }
            set
            {
                this.numSerieDispositivoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ticketbai:emision")]
    public partial class Entrega
    {

        private SujetaType sujetaField;

        private DetalleNoSujeta[] noSujetaField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SujetaType Sujeta
        {
            get
            {
                return this.sujetaField;
            }
            set
            {
                this.sujetaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public DetalleNoSujeta[] NoSujeta
        {
            get
            {
                return this.noSujetaField;
            }
            set
            {
                this.noSujetaField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ticketbai:emision")]
    public partial class SujetaType
    {

        private DetalleExentaType[] exentaField;

        private DetalleNoExentaType[] noExentaField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("DetalleExenta", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public DetalleExentaType[] Exenta
        {
            get
            {
                return this.exentaField;
            }
            set
            {
                this.exentaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("DetalleNoExenta", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public DetalleNoExentaType[] NoExenta
        {
            get
            {
                return this.noExentaField;
            }
            set
            {
                this.noExentaField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ticketbai:emision")]
    public partial class DetalleExentaType
    {

        private CausaExencionType causaExencionField;

        private string baseImponibleField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CausaExencionType CausaExencion
        {
            get
            {
                return this.causaExencionField;
            }
            set
            {
                this.causaExencionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BaseImponible
        {
            get
            {
                return this.baseImponibleField;
            }
            set
            {
                this.baseImponibleField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ticketbai:emision")]
    public enum CausaExencionType
    {

        /// <remarks/>
        E1,

        /// <remarks/>
        E2,

        /// <remarks/>
        E3,

        /// <remarks/>
        E4,

        /// <remarks/>
        E5,

        /// <remarks/>
        E6,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ticketbai:emision")]
    public partial class DetalleNoExentaType
    {

        private TipoOperacionSujetaNoExentaType tipoNoExentaField;

        private DetalleIVAType[] desgloseIVAField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TipoOperacionSujetaNoExentaType TipoNoExenta
        {
            get
            {
                return this.tipoNoExentaField;
            }
            set
            {
                this.tipoNoExentaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("DetalleIVA", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public DetalleIVAType[] DesgloseIVA
        {
            get
            {
                return this.desgloseIVAField;
            }
            set
            {
                this.desgloseIVAField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ticketbai:emision")]
    public enum TipoOperacionSujetaNoExentaType
    {

        /// <remarks/>
        S1,

        /// <remarks/>
        S2,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ticketbai:emision")]
    public partial class DetalleIVAType
    {

        private string baseImponibleField;

        private string tipoImpositivoField;

        private string cuotaImpuestoField;

        private string tipoRecargoEquivalenciaField;

        private string cuotaRecargoEquivalenciaField;

        private SiNoType operacionEnRecargoDeEquivalenciaORegimenSimplificadoField;

        private bool operacionEnRecargoDeEquivalenciaORegimenSimplificadoFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BaseImponible
        {
            get
            {
                return this.baseImponibleField;
            }
            set
            {
                this.baseImponibleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TipoImpositivo
        {
            get
            {
                return this.tipoImpositivoField;
            }
            set
            {
                this.tipoImpositivoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CuotaImpuesto
        {
            get
            {
                return this.cuotaImpuestoField;
            }
            set
            {
                this.cuotaImpuestoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TipoRecargoEquivalencia
        {
            get
            {
                return this.tipoRecargoEquivalenciaField;
            }
            set
            {
                this.tipoRecargoEquivalenciaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CuotaRecargoEquivalencia
        {
            get
            {
                return this.cuotaRecargoEquivalenciaField;
            }
            set
            {
                this.cuotaRecargoEquivalenciaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SiNoType OperacionEnRecargoDeEquivalenciaORegimenSimplificado
        {
            get
            {
                return this.operacionEnRecargoDeEquivalenciaORegimenSimplificadoField;
            }
            set
            {
                this.operacionEnRecargoDeEquivalenciaORegimenSimplificadoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OperacionEnRecargoDeEquivalenciaORegimenSimplificadoSpecified
        {
            get
            {
                return this.operacionEnRecargoDeEquivalenciaORegimenSimplificadoFieldSpecified;
            }
            set
            {
                this.operacionEnRecargoDeEquivalenciaORegimenSimplificadoFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ticketbai:emision")]
    public enum SiNoType
    {

        /// <remarks/>
        S,

        /// <remarks/>
        N,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ticketbai:emision")]
    public partial class DetalleNoSujeta
    {

        private CausaNoSujetaType causaField;

        private string importeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CausaNoSujetaType Causa
        {
            get
            {
                return this.causaField;
            }
            set
            {
                this.causaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Importe
        {
            get
            {
                return this.importeField;
            }
            set
            {
                this.importeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ticketbai:emision")]
    public enum CausaNoSujetaType
    {

        /// <remarks/>
        OT,

        /// <remarks/>
        RL,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ticketbai:emision")]
    public partial class PrestacionServicios
    {

        private SujetaType sujetaField;

        private DetalleNoSujeta[] noSujetaField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SujetaType Sujeta
        {
            get
            {
                return this.sujetaField;
            }
            set
            {
                this.sujetaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public DetalleNoSujeta[] NoSujeta
        {
            get
            {
                return this.noSujetaField;
            }
            set
            {
                this.noSujetaField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ticketbai:emision")]
    public partial class DesgloseTipoOperacionType
    {

        private PrestacionServicios prestacionServiciosField;

        private Entrega entregaField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PrestacionServicios PrestacionServicios
        {
            get
            {
                return this.prestacionServiciosField;
            }
            set
            {
                this.prestacionServiciosField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Entrega Entrega
        {
            get
            {
                return this.entregaField;
            }
            set
            {
                this.entregaField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ticketbai:emision")]
    public partial class DesgloseFacturaType
    {

        private SujetaType sujetaField;

        private DetalleNoSujeta[] noSujetaField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SujetaType Sujeta
        {
            get
            {
                return this.sujetaField;
            }
            set
            {
                this.sujetaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public DetalleNoSujeta[] NoSujeta
        {
            get
            {
                return this.noSujetaField;
            }
            set
            {
                this.noSujetaField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ticketbai:emision")]
    public partial class TipoDesgloseType
    {

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DesgloseFactura", typeof(DesgloseFacturaType), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("DesgloseTipoOperacion", typeof(DesgloseTipoOperacionType), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ticketbai:emision")]
    public partial class IDClaveType
    {

        private IdOperacionesTrascendenciaTributariaType claveRegimenIvaOpTrascendenciaField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IdOperacionesTrascendenciaTributariaType ClaveRegimenIvaOpTrascendencia
        {
            get
            {
                return this.claveRegimenIvaOpTrascendenciaField;
            }
            set
            {
                this.claveRegimenIvaOpTrascendenciaField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ticketbai:emision")]
    public enum IdOperacionesTrascendenciaTributariaType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("01")]
        Item01,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("02")]
        Item02,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("03")]
        Item03,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("04")]
        Item04,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("05")]
        Item05,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("06")]
        Item06,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("07")]
        Item07,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("08")]
        Item08,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("09")]
        Item09,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("10")]
        Item10,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("11")]
        Item11,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("12")]
        Item12,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("13")]
        Item13,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("14")]
        Item14,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("15")]
        Item15,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("51")]
        Item51,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("52")]
        Item52,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("53")]
        Item53,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ticketbai:emision")]
    public partial class IDDetalleFacturaType
    {

        private string descripcionDetalleField;

        private string cantidadField;

        private string importeUnitarioField;

        private string descuentoField;

        private string importeTotalField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DescripcionDetalle
        {
            get
            {
                return this.descripcionDetalleField;
            }
            set
            {
                this.descripcionDetalleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Cantidad
        {
            get
            {
                return this.cantidadField;
            }
            set
            {
                this.cantidadField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ImporteUnitario
        {
            get
            {
                return this.importeUnitarioField;
            }
            set
            {
                this.importeUnitarioField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Descuento
        {
            get
            {
                return this.descuentoField;
            }
            set
            {
                this.descuentoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ImporteTotal
        {
            get
            {
                return this.importeTotalField;
            }
            set
            {
                this.importeTotalField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ticketbai:emision")]
    public partial class DatosFacturaType
    {

        private string fechaOperacionField;

        private string descripcionFacturaField;

        private IDDetalleFacturaType[] detallesFacturaField;

        private string importeTotalFacturaField;

        private string retencionSoportadaField;

        private string baseImponibleACosteField;

        private IDClaveType[] clavesField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FechaOperacion
        {
            get
            {
                return this.fechaOperacionField;
            }
            set
            {
                this.fechaOperacionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DescripcionFactura
        {
            get
            {
                return this.descripcionFacturaField;
            }
            set
            {
                this.descripcionFacturaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("IDDetalleFactura", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public IDDetalleFacturaType[] DetallesFactura
        {
            get
            {
                return this.detallesFacturaField;
            }
            set
            {
                this.detallesFacturaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ImporteTotalFactura
        {
            get
            {
                return this.importeTotalFacturaField;
            }
            set
            {
                this.importeTotalFacturaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RetencionSoportada
        {
            get
            {
                return this.retencionSoportadaField;
            }
            set
            {
                this.retencionSoportadaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BaseImponibleACoste
        {
            get
            {
                return this.baseImponibleACosteField;
            }
            set
            {
                this.baseImponibleACosteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("IDClave", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public IDClaveType[] Claves
        {
            get
            {
                return this.clavesField;
            }
            set
            {
                this.clavesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ticketbai:emision")]
    public partial class IDFacturaRectificadaSustituidaType
    {

        private string serieFacturaField;

        private string numFacturaField;

        private string fechaExpedicionFacturaField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SerieFactura
        {
            get
            {
                return this.serieFacturaField;
            }
            set
            {
                this.serieFacturaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NumFactura
        {
            get
            {
                return this.numFacturaField;
            }
            set
            {
                this.numFacturaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FechaExpedicionFactura
        {
            get
            {
                return this.fechaExpedicionFacturaField;
            }
            set
            {
                this.fechaExpedicionFacturaField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ticketbai:emision")]
    public partial class ImporteRectificacionSustitutivaType
    {

        private string baseRectificadaField;

        private string cuotaRectificadaField;

        private string cuotaRecargoRectificadaField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BaseRectificada
        {
            get
            {
                return this.baseRectificadaField;
            }
            set
            {
                this.baseRectificadaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CuotaRectificada
        {
            get
            {
                return this.cuotaRectificadaField;
            }
            set
            {
                this.cuotaRectificadaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CuotaRecargoRectificada
        {
            get
            {
                return this.cuotaRecargoRectificadaField;
            }
            set
            {
                this.cuotaRecargoRectificadaField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ticketbai:emision")]
    public partial class FacturaRectificativaType
    {

        private ClaveTipoFacturaType codigoField;

        private ClaveTipoRectificativaType tipoField;

        private ImporteRectificacionSustitutivaType importeRectificacionSustitutivaField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClaveTipoFacturaType Codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClaveTipoRectificativaType Tipo
        {
            get
            {
                return this.tipoField;
            }
            set
            {
                this.tipoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ImporteRectificacionSustitutivaType ImporteRectificacionSustitutiva
        {
            get
            {
                return this.importeRectificacionSustitutivaField;
            }
            set
            {
                this.importeRectificacionSustitutivaField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ticketbai:emision")]
    public enum ClaveTipoFacturaType
    {

        /// <remarks/>
        R1,

        /// <remarks/>
        R2,

        /// <remarks/>
        R3,

        /// <remarks/>
        R4,

        /// <remarks/>
        R5,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ticketbai:emision")]
    public enum ClaveTipoRectificativaType
    {

        /// <remarks/>
        S,

        /// <remarks/>
        I,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ticketbai:emision")]
    public partial class CabeceraFacturaType
    {

        private string serieFacturaField;

        private string numFacturaField;

        private string fechaExpedicionFacturaField;

        private string horaExpedicionFacturaField;

        private SiNoType facturaSimplificadaField;

        private bool facturaSimplificadaFieldSpecified;

        private SiNoType facturaEmitidaSustitucionSimplificadaField;

        private bool facturaEmitidaSustitucionSimplificadaFieldSpecified;

        private FacturaRectificativaType facturaRectificativaField;

        private IDFacturaRectificadaSustituidaType[] facturasRectificadasSustituidasField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SerieFactura
        {
            get
            {
                return this.serieFacturaField;
            }
            set
            {
                this.serieFacturaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NumFactura
        {
            get
            {
                return this.numFacturaField;
            }
            set
            {
                this.numFacturaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FechaExpedicionFactura
        {
            get
            {
                return this.fechaExpedicionFacturaField;
            }
            set
            {
                this.fechaExpedicionFacturaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HoraExpedicionFactura
        {
            get
            {
                return this.horaExpedicionFacturaField;
            }
            set
            {
                this.horaExpedicionFacturaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SiNoType FacturaSimplificada
        {
            get
            {
                return this.facturaSimplificadaField;
            }
            set
            {
                this.facturaSimplificadaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FacturaSimplificadaSpecified
        {
            get
            {
                return this.facturaSimplificadaFieldSpecified;
            }
            set
            {
                this.facturaSimplificadaFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SiNoType FacturaEmitidaSustitucionSimplificada
        {
            get
            {
                return this.facturaEmitidaSustitucionSimplificadaField;
            }
            set
            {
                this.facturaEmitidaSustitucionSimplificadaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FacturaEmitidaSustitucionSimplificadaSpecified
        {
            get
            {
                return this.facturaEmitidaSustitucionSimplificadaFieldSpecified;
            }
            set
            {
                this.facturaEmitidaSustitucionSimplificadaFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FacturaRectificativaType FacturaRectificativa
        {
            get
            {
                return this.facturaRectificativaField;
            }
            set
            {
                this.facturaRectificativaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("IDFacturaRectificadaSustituida", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public IDFacturaRectificadaSustituidaType[] FacturasRectificadasSustituidas
        {
            get
            {
                return this.facturasRectificadasSustituidasField;
            }
            set
            {
                this.facturasRectificadasSustituidasField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ticketbai:emision")]
    public partial class Factura
    {

        private CabeceraFacturaType cabeceraFacturaField;

        private DatosFacturaType datosFacturaField;

        private TipoDesgloseType tipoDesgloseField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CabeceraFacturaType CabeceraFactura
        {
            get
            {
                return this.cabeceraFacturaField;
            }
            set
            {
                this.cabeceraFacturaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DatosFacturaType DatosFactura
        {
            get
            {
                return this.datosFacturaField;
            }
            set
            {
                this.datosFacturaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TipoDesgloseType TipoDesglose
        {
            get
            {
                return this.tipoDesgloseField;
            }
            set
            {
                this.tipoDesgloseField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ticketbai:emision")]
    public partial class IDDestinatario
    {

        private object itemField;

        private string apellidosNombreRazonSocialField;

        private string codigoPostalField;

        private string direccionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IDOtro", typeof(IDOtro), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("NIF", typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ApellidosNombreRazonSocial
        {
            get
            {
                return this.apellidosNombreRazonSocialField;
            }
            set
            {
                this.apellidosNombreRazonSocialField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodigoPostal
        {
            get
            {
                return this.codigoPostalField;
            }
            set
            {
                this.codigoPostalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Direccion
        {
            get
            {
                return this.direccionField;
            }
            set
            {
                this.direccionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ticketbai:emision")]
    public partial class Emisor
    {

        private string nIFField;

        private string apellidosNombreRazonSocialField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NIF
        {
            get
            {
                return this.nIFField;
            }
            set
            {
                this.nIFField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ApellidosNombreRazonSocial
        {
            get
            {
                return this.apellidosNombreRazonSocialField;
            }
            set
            {
                this.apellidosNombreRazonSocialField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ticketbai:emision")]
    public partial class Sujetos
    {

        private Emisor emisorField;

        private IDDestinatario[] destinatariosField;

        private SiNoType variosDestinatariosField;

        private bool variosDestinatariosFieldSpecified;

        private EmitidaPorTercerosType emitidaPorTercerosODestinatarioField;

        private bool emitidaPorTercerosODestinatarioFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Emisor Emisor
        {
            get
            {
                return this.emisorField;
            }
            set
            {
                this.emisorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public IDDestinatario[] Destinatarios
        {
            get
            {
                return this.destinatariosField;
            }
            set
            {
                this.destinatariosField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SiNoType VariosDestinatarios
        {
            get
            {
                return this.variosDestinatariosField;
            }
            set
            {
                this.variosDestinatariosField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VariosDestinatariosSpecified
        {
            get
            {
                return this.variosDestinatariosFieldSpecified;
            }
            set
            {
                this.variosDestinatariosFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EmitidaPorTercerosType EmitidaPorTercerosODestinatario
        {
            get
            {
                return this.emitidaPorTercerosODestinatarioField;
            }
            set
            {
                this.emitidaPorTercerosODestinatarioField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EmitidaPorTercerosODestinatarioSpecified
        {
            get
            {
                return this.emitidaPorTercerosODestinatarioFieldSpecified;
            }
            set
            {
                this.emitidaPorTercerosODestinatarioFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ticketbai:emision")]
    public enum EmitidaPorTercerosType
    {

        /// <remarks/>
        N,

        /// <remarks/>
        T,

        /// <remarks/>
        D,
    }

}
